/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.data;
import static gui.customer_reg.jTable1;
import java.io.InputStream;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author Theekshana
 */
public class ChannlingCustomer_report_3 extends javax.swing.JFrame {

    /**
     * Creates new form Customer_report_1
     */
    public ChannlingCustomer_report_3() {
        initComponents();
        report();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "Channeling Customer", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Maiandra GD", 1, 18))); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChannlingCustomer_report_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChannlingCustomer_report_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChannlingCustomer_report_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChannlingCustomer_report_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChannlingCustomer_report_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void loadcustomer() {
        ResultSet rs = data.search("SELECT * FROM `customer`");
        TableModel tm = customer_reg.jTable1.getModel();
        DefaultTableModel dtm = (DefaultTableModel) tm;
        dtm.setRowCount(0);

        try {
            while (rs.next()) {
                Vector<String> vr = new Vector<>();
                vr.add(rs.getString("mobile"));
                vr.add(rs.getString("name"));
                vr.add(rs.getString("email"));
                vr.add(rs.getString("address"));

                dtm.addRow(vr);
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public void report() {

        try {
            InputStream is = null;
            String path = "src//reports//Channling_customer.jasper";
            try {
                is = getClass().getResourceAsStream(path);
                String id = Chan_report.jLabel27.getText();
                String name = Chan_report.jLabel28.getText();
                String r_sph = Chan_report.jTextField15.getText();
                String r_cyl = Chan_report.jTextField16.getText();
                String r_axis = Chan_report.jTextField17.getText();
                String r_vd = Chan_report.jTextField18.getText();
                String r_va = Chan_report.jTextField19.getText();
                String l_sph = Chan_report.jTextField20.getText();
                String l_cyl = Chan_report.jTextField21.getText();
                String l_axis = Chan_report.jTextField22.getText();
                String l_vd = Chan_report.jTextField23.getText();
                String l_va = Chan_report.jTextField24.getText();

                HashMap<String, Object> map = new HashMap<>();
                map.put("Parameter1", id);
                map.put("Parameter2", name);
                map.put("Parameter3", r_sph);
                map.put("Parameter4", r_cyl);
                map.put("Parameter5", r_axis);
                map.put("Parameter6", r_vd);
                map.put("Parameter7", r_va);
                map.put("Parameter8", l_sph);
                map.put("Parameter9", l_cyl);
                map.put("Parameter10", l_axis);
                map.put("Parameter11", l_vd);
                map.put("Parameter12", l_va);

                JREmptyDataSource dataSource = new JREmptyDataSource();

                JasperPrint print = JasperFillManager.fillReport(path, map, dataSource);
                JRViewer viewer = new JRViewer(print);
                jPanel1.add(viewer);
                jPanel1.revalidate();
            } finally {
                try {
                    is.close();
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }
}
