/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import database.data;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sehan Iroshana
 */
public class dr_payment extends javax.swing.JPanel {

    /** Creates new form SettingsBackColor */
    public dr_payment() {
        initComponents();
        drpayment();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 252, 188));
        setMaximumSize(new java.awt.Dimension(610, 500));
        setMinimumSize(new java.awt.Dimension(610, 500));
        setPreferredSize(new java.awt.Dimension(610, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jLabel6.setText("Update Doctor Payment");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 36));

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("New Payment : ");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jTextField5.setBackground(new java.awt.Color(153, 153, 153));
        jTextField5.setFont(new java.awt.Font("Maiandra GD", 0, 22)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 180, -1));

        jTextField6.setFont(new java.awt.Font("Maiandra GD", 0, 22)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 180, -1));

        jButton7.setBackground(new java.awt.Color(27, 20, 100));
        jButton7.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("payment");
        jButton7.setContentAreaFilled(false);
        jButton7.setOpaque(true);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String txt = jTextField6.getText();
        try {
             data.iud("Update `dr_payment` SET `payment` = '"+txt+"'");
             JOptionPane.showMessageDialog(this, "add", "Success", JOptionPane.INFORMATION_MESSAGE);
             drpayment();
             jTextField6.setText("");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

    
    public void  drpayment(){
    
            ResultSet rs = data.search("SELECT * FROM `dr_payment`");
            try {
                if(jTextField5 == null){
                jTextField5.setText("0");
                
                }else{
            if(rs.next()){
            jTextField5.setText(rs.getString("payment"));
            
            }
                }
        } catch (Exception e) {
                System.out.println(e);
        }
    
    
    }
    
}
