
package gui;

import database.data;
import static gui.channeling.jTable1;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/**
 *
 * @author Theekshana
 */
public class viewemployee extends javax.swing.JPanel {

    static viewemployee r;

    public viewemployee() {
        initComponents();
        design();
        loademployee();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        nic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(1875, 32));

        jTable2.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIC", "First Name", "Last Name", "DOB", "Contact No", "Email", "Bank", "Account No"
            }
        ));
        jTable2.setFocusable(false);
        jTable2.setRowHeight(25);
        jTable2.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable2.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable2.setShowVerticalLines(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 382, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 1000, 420));

        jButton1.setBackground(new java.awt.Color(44, 102, 176));
        jButton1.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Report");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 180, 190, 40));

        nic.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        nic.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nic.setText(" ");
        nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicKeyReleased(evt);
            }
        });
        add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, 215, 40));

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel3.setText("All Employee ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, -1, 41));

        jButton2.setBackground(new java.awt.Color(44, 102, 176));
        jButton2.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Search");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, 190, 40));

        jLabel4.setBackground(new java.awt.Color(32, 46, 128));
        jLabel4.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("All Employee");
        jLabel4.setOpaque(true);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 41));
    }// </editor-fold>//GEN-END:initComponents

    private void nicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyReleased
        String text = nic.getText();
        try {
            ResultSet rs = database.data.search("SELECT * FROM employee WHERE `nic` LIKE '%"+text+"%'");
            TableModel tm = jTable2.getModel();
            DefaultTableModel dtm = (DefaultTableModel)tm;
            dtm.setRowCount(0);
            while (rs.next()) {                
                 Vector<String> vr = new Vector<>();
               vr.add(rs.getString("nic"));
                vr.add(rs.getString("efname"));
                vr.add(rs.getString("lname"));
                vr.add(rs.getString("dob"));
                vr.add(rs.getString("mobile"));
                vr.add(rs.getString("email"));

                ResultSet rs1 = database.data.search("SELECT `name` FROM bank WHERE bankId = '" + rs.getString("bank_bankId") + "';");

                if (rs1.next()) {
                    vr.add(rs1.getString("name"));

                }
                vr.add(rs.getString("accountNo"));
                dtm.addRow(vr);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_nicKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Employee_report_5 emp = new Employee_report_5();
       emp.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public static viewemployee viem1() {
        if (r == null) {
            r = new viewemployee();
        }
        return r;
    }

      public void design() {

        Font font = new Font("Maiandra GD", Font.BOLD, 18);
        JTableHeader header = jTable2.getTableHeader();
        header.setFont(font);
        header.setOpaque(false);
        header.setBackground(new Color(9,0,82));
        header.setForeground(new Color(255,255,255));
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    static javax.swing.JTable jTable2;
    private javax.swing.JTextField nic;
    // End of variables declaration//GEN-END:variables

    public void loademployee(){
    ResultSet rs = database.data.search("SELECT * FROM employee");
        TableModel tdm = jTable2.getModel();
        DefaultTableModel dtm = (DefaultTableModel) tdm;
        dtm.setRowCount(0);

        try {
            while (rs.next()) {
                Vector<String> vr = new Vector<>();
                vr.add(rs.getString("nic"));
                vr.add(rs.getString("efname"));
                vr.add(rs.getString("lname"));
                vr.add(rs.getString("dob"));
                vr.add(rs.getString("mobile"));
                vr.add(rs.getString("email"));

                ResultSet rs1 = database.data.search("SELECT `name` FROM bank WHERE bankId = '" + rs.getString("bank_bankId") + "';");

                if (rs1.next()) {
                    vr.add(rs1.getString("name"));

                }
                vr.add(rs.getString("accountNo"));
                dtm.addRow(vr);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    
    }

    
}
